### ISSUE TITLE
Failed to activate the coffee-compiler package

### ISSUE THREAD

**Issue by marnen** [forabi/coffee-compiler#5]
[Enter steps to reproduce below:]

1. Try to execute Coffee Compiler on a CoffeeScript file in the editor.

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.4
**Thrown From**: [coffee-compiler](https://github.com/forabi/coffee-compiler) package, v0.11.0

### Stack Trace

Failed to activate the coffee-compiler package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
  at Object.module.exports.activate (/Users/mlaibowkoser/.atom/packages/coffee-compiler/lib/coffee-compiler.coffee:7:27)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:240:19)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:772:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:222:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
  at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:241:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:177:20)

```

### Commands

```
     -2:04.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:02.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:59.4.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  2x -1:55.4.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:47.4.0 core:save (atom-text-editor.editor.is-focused)
     -1:24.5.0 core:select-all (atom-text-editor.editor.is-focused)
     -1:23.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -1:21.9.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -1:21.9.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -1:19.8.0 settings-view:open (atom-text-editor.editor.is-focused)
  3x -1:15.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:05.0 core:close (atom-text-editor.editor.mini.is-focused)
     -0:03.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.4.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.6.0 coffee-compiler:compile (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
blame, v0.1.2
coffee-compiler, v0.11.0
cucumber, v0.5.0
git-plus, v5.2.2
language-haml, v0.21.0
make-coffee, v0.1.1
monokai, v0.14.0
regex-railroad-diagram, v0.8.3
tree-view-git-status, v0.1.1

# Dev
No dev packages
```

**Comment by forabi** [comment]
Thanks for taking time to report the bug. Unfortunately I cannot maintain the package due to lack of time. The package is now unpublished. Consider using an alternative like [atom-coffee-compiler](https://github.com/adrianlee44/atom-coffee-compile).

**Comment by marnen** [comment]
So why are you closing this instead of leaving it open for a future maintainer?

**Comment by forabi** [comment]
Better alternatives have been introduced since this package was published. Also, unpublishing my package would allow anyone to fork this repository and republish a new package based on mine without me having to review/merge PRs.
